### ISSUE TITLE
OscamStatus: Undefined variable w on LogDataScreen

### ISSUE THREAD

**Issue by athoik** [E2OpenPlugins/e2openplugin-OscamStatus#9]
Hi, 

Variable w(idth) is not defined in function LogDataScreen, resulting in the following crash on non FULLHD skins.

```
Plugin  Extensions/OscamStatus failed to load: name 'w' is not defined
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 52, in readPluginList
    plugin = my_import('.'.join(["Plugins", c, pluginname, "plugin"]))
  File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
    mod = __import__(name)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OscamStatus/plugin.py", line 1082, in <module>
    class LogDataScreen(DownloadXMLScreen):
  File "/usr/lib/enigma2/python/Plugins/Extensions/OscamStatus/plugin.py", line 1089, in LogDataScreen
    elif w == 1280:
NameError: name 'w' is not defined
```
Could you please add `w = getDesktop(0).size().width()` on line 1080 to fix it?

**Comment by pr2git** [comment]
Hi,

Thanks done:
https://github.com/E2OpenPlugins/e2openplugin-OscamStatus/commit/7cade0783b41cf56989425cbebab11579f3e4bfb

But a full review of the non HD screens should be done, I have so far focused on HD skin.
